services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glucose-data-api-dev
    networks:
      - glucose-data-api
    ports:
      - '7091:8000'
    env_file:
      - config/.env.example
    volumes:
      - ./:/code/
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'

  db:
    image: mysql:8.0.34
    container_name: glucose-data-api-db
    networks:
      - glucose-data-api
    environment:
      MYSQL_USER: db_user
      MYSQL_PASSWORD: fMvT82Pr1A7UntrzUDK
      MYSQL_ROOT_PASSWORD: SD1pgMtt5CYy8YsKl5g
      MYSQL_DATABASE: glucose_records
    volumes:
      - "./db_data:/var/lib/mysql"

  db-test:
    image: mysql:8.0.34
    container_name: glucose-data-api-db-test
    networks:
      - glucose-data-api
    environment:
      MYSQL_USER: db_user_test
      MYSQL_PASSWORD: Zds5DuF6TLbZexOZHjP
      MYSQL_ROOT_PASSWORD: aqudMiqDr8rVaxffJ68
      MYSQL_DATABASE: glucose_records_test

networks:
  glucose-data-api:
    name: glucose-data-api
