"""drop constraint on user_id and timestamp

Revision ID: 513ade8ac045
Revises: b5ffa308bf64
Create Date: 2025-05-10 14:00:43.438548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513ade8ac045'
down_revision: Union[str, None] = 'b5ffa308bf64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_timestamp', table_name='user_glucose_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_timestamp', 'user_glucose_data', ['user_id', 'device_timestamp'], unique=True)
    # ### end Alembic commands ###
