"""fix some fields

Revision ID: 87da75f225c6
Revises: d619f5561d13
Create Date: 2025-05-10 13:35:31.002761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87da75f225c6'
down_revision: Union[str, None] = 'd619f5561d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_glucose_data', 'glucose_value_history',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('user_id', table_name='user_glucose_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'user_glucose_data', ['user_id'], unique=True)
    op.alter_column('user_glucose_data', 'glucose_value_history',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
