"""add unique constraint on user_id and timestamp

Revision ID: b5ffa308bf64
Revises: 87da75f225c6
Create Date: 2025-05-10 13:49:59.381302

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5ffa308bf64"
down_revision: Union[str, None] = "87da75f225c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_timestamp", "user_glucose_data", ["user_id", "device_timestamp"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_timestamp", "user_glucose_data", type_="unique")
    # ### end Alembic commands ###
