"""add user_glucose_data table

Revision ID: d619f5561d13
Revises:
Create Date: 2025-05-10 12:52:41.642261

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d619f5561d13"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_glucose_data",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("device", sa.String(length=100), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("device_timestamp", sa.DateTime(), nullable=False),
        sa.Column("record_type", sa.Integer(), nullable=False),
        sa.Column("glucose_value_history", sa.Integer(), nullable=False),
        sa.Column("glucose_scan", sa.Float(), nullable=True),
        sa.Column("non_numeric_fast_insulin", sa.Text(), nullable=True),
        sa.Column("fast_insulin_units", sa.Float(), nullable=True),
        sa.Column("non_numeric_food", sa.Text(), nullable=True),
        sa.Column("carbs_grams", sa.Float(), nullable=True),
        sa.Column("carbs_portions", sa.Float(), nullable=True),
        sa.Column("non_numeric_long_insulin", sa.Text(), nullable=True),
        sa.Column("long_insulin_units", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("glucose_teststrip", sa.Float(), nullable=True),
        sa.Column("ketone", sa.Float(), nullable=True),
        sa.Column("meal_insulin", sa.Float(), nullable=True),
        sa.Column("correction_insulin", sa.Float(), nullable=True),
        sa.Column("insulin_change_by_user", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_glucose_data")
    # ### end Alembic commands ###
